= Server Preparation for Ubuntu 18.04
:hash-installation: http://php.net/manual/en/hash.installation.php
:mcrypt-link-url: https://websiteforstudents.com/install-php-7-2-mcrypt-module-on-ubuntu-18-04-lts/
:mcrypt-pecl-url: https://pecl.php.net/package/mcrypt
:discover-samba-hosts: https://ubuntuforums.org/showthread.php?t=2384959
:install-mariadb-latest: https://downloads.mariadb.org/mariadb/repositories/#

== Web Server and PHP

You only need to install _one_ of the following web servers.
 
=== Apache Web server + PHP (supported)

The following command installs the Apache web server and PHP.

[source,console]
----
sudo apt install -y php libapache2-mod-php apache2
----

=== Apache Web Server and PHP-FPM (unsupported)

The following command installs and enables the Apache web server with php-fpm.

[TIP] 
====
This setup can be used in high throughput environments. 
For performance comparison details, please see the following https://www.cloudways.com/blog/php-fpm-on-cloud/[link].
====

// TODO: check if dismod and enmod accept multiple arguments
[source,console]
----
sudo apt install -y php-fpm apache2
sudo a2enmod proxy_fcgi
sudo a2enconf php7.2-fpm
sudo a2dismod php7.2
sudo a2dismod mpm_prefork
sudo a2enmod mpm_event
sudo a2enmod http2
sudo service apache2 restart
----

For examples of how to configure this setup, consult the following links:

* http://httpd.apache.org/docs/2.4/mod/mod_proxy.html#handler
* https://httpd.apache.org/docs/2.4/mod/mod_proxy_fcgi.html
* https://wiki.apache.org/httpd/PHP-FPM

=== NGINX Web Server and PHP-FPM (unsupported)

The following command installs the NGINX web server and php-fpm.

[source,console]
----
sudo apt install php-fpm nginx
----

For details of how to configure NGINX, please see the xref:installation/nginx_configuration.adoc[NGINX configuration documentation].

== Common Prerequisites

[source,console]
----
sudo apt install -y smbclient redis-server unzip php-mysql php-mbstring \
  php-gettext php-intl php-redis php-imagick php-igbinary php-gmp \
  php-curl php-gd php-zip php-imap php-ldap php-bz2 php-phpseclib
----

== HASH Message Digest Framework

This framework does not need any manual intervention anymore, because the Hash extension is 

* Bundled and compiled into PHP 5.1.2 by default As of PHP
* A core PHP 7.4.0 extension, so it is always enabled

For more information see following {hash-installation}[PHP’s Hash installation documentation].

== Exif Library

This library should be already part of PHP 7.2.
Please check the `mods_available` directory, and if the Exif extension is installed and enabled.
To do so, run the following command, which lists all enabled PHP extensions:

[source,console]
----
ls `php -i | grep "^extension_dir" | sed -e 's/.*=> //'`
----

== PHP 7.2 Cryptography Library

There is no need to install additional cryptographic libraries, such as `php-libsodium` and `mcrypt`, in PHP 7.2 as Sodium and OpenSSL are already part of the PHP 7.2 core.
Additionally, Mcrypt is deprecated and moved to PECL.
However, if you do need to install them, then you can find out how to do so below.

xref:#php-libsodium[php-libsodium]
xref:#mcrypt-php-library[Mcrypt PHP Library]

=== php-libsodium

If you get error messages such as `PHP Fatal error: sodium_init() in Unknown on line 0`, you might have installed `php-libsodium` separately.
This error does not do any harm, but can be annoying.
Additionally, it will fill up your logs.

To get rid of it, you have to uninstall `php-libsodium`, as `sodium` is already part of the PHP 7.2 core.
You can do this by running the following command:

[source,console]
----
sudo apt remove php-libsodium
----

You can check if it has been removed by invoking `php -v`, which should not return this error message anymore.
In addition, you can check for the existence of `sodium` with the following command:

[source,console]
----
php -i | grep "sodium"
sodium
sodium support => enabled
libsodium headers version => 1.0.16
libsodium library version => 1.0.16
----

=== Mcrypt PHP Library

Here are the steps for installing the `mcrypt` library, in case it is required.
Referencing the following {mcrypt-link-url}[link], some steps are adopted.
Check the `mcrypt` version you want to use in {mcrypt-pecl-url}[PECL's Mcrypt documentation].

[source,console]
----
sudo apt install php-dev libmcrypt-dev php-pear
sudo pecl channel-update pecl.php.net
sudo pecl install mcrypt-1.0.2
----

- Create a new file `mcrypt.ini` in `/etc/php/7.2/mods-available` with following content: `extension=mcrypt.so`
- Create in any subdirectory of `7.2` containing a `conf.d` directory a symbolic link: `sudo ln -s /etc/php/7.2/mods-available/mcrypt.ini 20-mcrypt.ini`
- You need to restart php and your web server, example based on NGINX: +
`sudo service php7.2-fpm restart` +
`sudo service nginx restart`

== libsmbclient-php Library

`libsmbclient-php` is a PHP extension that uses Samba's libsmbclient library to provide Samba related functions to PHP programs.

[source,console]
----
sudo apt install php-dev libsmbclient-dev php-pear
sudo pecl channel-update pecl.php.net
sudo pecl install smbclient
----

- Create a new file `smbclient.ini` in `/etc/php/7.2/mods-available` with following content: +
`extension=smbclient.so`
- Create in any subdirectory of `7.2` containing a `conf.d` directory a symbolic link: +
`sudo ln -s /etc/php/7.2/mods-available/smbclient.ini 20-smbclient.ini` +
- You need to restart php and your web server, example based on NGINX: +
`sudo service php7.2-fpm restart` +
`sudo service nginx restart`

NOTE: Due to a change in the minimum protocol version used in the samba client in
Ubuntu 18.04, you may not get a valid connection in ownCloud (red box at the mount
definition and/or cannot list directory content). 
In this case, you have to add the following to `/etc/samba/smb.cnf` below the `workgroup =` statement: `client max protocol = NT1`. 
For more information see: {discover-samba-hosts}[Bionic Beaver can not discover samba hosts]

== Database MariaDB

For how to install the latest stable release of MariaDB see following {install-mariadb-latest}[link].
In case you want to install `phpmyadmin` as a graphical interface for administrating the database:

[source,console]
----
sudo apt install phpmyadmin
----

== Useful Tips

If you have network resources like NFS based mounts, and you want to make sure that the database server or the web server only starts after the resource has been mounted, look for the following example.
Example based on an NFS mount you want to be available before the service  with <name.service> starts.

* Add `_netdev` to the list of NFS mountpoint options in your fstab. This option makes sure that the mount will happen __after__ the network is up. `resource:path on local_path type nfs (<your options>,_netdev)`
* Make sure that all mounts in fstab are mounted by running `sudo mount -a`.
* Run `systemctl list-units | grep -nP "\.mount"` and look for the mount you want to be up. `folder.mount loaded active mounted local_path` +
Where `folder.mount` and `local_path` are examples. 
* In `/etc/systemd/system/<name.service>` add `folder.mount` after the directive `After=network.target`.
Example: `After=network.target folder.mount`
* Run `sudo systemctl daemon-reload`
* Restart your service by invoking `sudo system <your service> restart`.
